#!/bin/bash

chmod 775 /data

# Create directory for bind config
mkdir -p /data/bind
chown -R root:bind /data/bind

# Populate default bind configuration if it does not exist
if [ ! -d /data/bind/etc ]; then
  mv /etc/bind /data/bind/etc
fi
rm -rf /etc/bind
ln -sf /data/bind/etc /etc/bind

if [ ! -d /data/bind/lib ]; then
  mkdir -p /data/bind/lib
  chown root:bind /data/bind/lib
fi
rm -rf /var/lib/bind
ln -sf /data/bind/lib /var/lib/bind

echo "Starting named..."
mkdir -m 0775 -p /var/run/named
chown root:bind /var/run/named
touch /var/log/query.log
chown bind /var/log/query.log
exec /usr/sbin/named -u bind -g
