#!/bin/bash

# Copy configuration files if not yet done.
if [ -e /opt/pascalbod/bindInitFlag ] ; then
  echo "Bind configuration already initialized"
else
  echo "Starting configuration..."
  # Ensure right ownership.
  chmod -R 775 /data/bind
  chown -R root:bind /data/bind
  cp /data/bind/etc/* /etc/bind/
  mkdir -p /opt/pascalbod
  touch /opt/pascalbod/bindInitFlag
  echo "Configuration done"
fi

echo "Starting named..."
mkdir -m 0775 -p /var/run/named
chown root:bind /var/run/named
touch /var/log/query.log
chown bind /var/log/query.log
exec /usr/sbin/named -u bind -f
